create table password_reset_codes (
  id bigint generated by default as identity primary key,
  user_id bigint not null references app_users(id),
  code_hash varchar(255) not null,
  expires_at timestamp not null,
  used_at timestamp,
  attempts integer not null default 0,
  created_at timestamp not null default now()
);

create index idx_password_reset_codes_user_id on password_reset_codes(user_id);
create index idx_password_reset_codes_expires_at on password_reset_codes(expires_at);
