create table problem_reports (
  id bigint generated by default as identity primary key,
  title varchar(180) not null,
  location varchar(80) not null,
  category varchar(80) not null,
  priority varchar(30) not null,
  status varchar(40) not null,
  description text not null,
  attachment_name varchar(220),
  resident_id bigint references residents(id),
  house_id bigint references houses(id),
  created_by bigint references app_users(id),
  created_at timestamp not null default now(),
  updated_at timestamp not null default now()
);

create index idx_problem_reports_status on problem_reports(status);
create index idx_problem_reports_house on problem_reports(house_id);
create index idx_problem_reports_created_at on problem_reports(created_at);
