create table direct_receipts (
  id bigint generated by default as identity primary key,
  gateway varchar(40) not null,
  gateway_payment_id varchar(120) not null,
  external_reference varchar(120),
  category varchar(80) not null,
  description varchar(220) not null,
  amount numeric(12, 2) not null,
  reference_month varchar(7) not null,
  received_at timestamp not null,
  status varchar(30) not null,
  receipt_url text,
  payload_json text,
  created_at timestamp not null default now(),
  updated_at timestamp not null default now(),
  constraint uk_direct_receipt_gateway_payment unique (gateway, gateway_payment_id)
);

create index idx_direct_receipts_month_status on direct_receipts(reference_month, status);
create index idx_direct_receipts_received_at on direct_receipts(received_at);
