create table excluded_gateway_payments (
  id bigint generated by default as identity primary key,
  gateway varchar(40) not null,
  gateway_payment_id varchar(120) not null,
  reason varchar(220),
  created_at timestamp not null default now(),
  constraint uk_excluded_gateway_payment unique (gateway, gateway_payment_id)
);
