alter table budgets add column voting_closed_at timestamp;

create table budget_votes (
  id bigint generated by default as identity primary key,
  budget_id bigint not null references budgets(id),
  house_id bigint not null references houses(id),
  resident_id bigint not null references residents(id),
  vote varchar(20) not null,
  created_at timestamp not null default now(),
  updated_at timestamp not null default now(),
  constraint uk_budget_vote_house unique (budget_id, house_id)
);
