create table houses (
  id bigint generated by default as identity primary key,
  number integer not null unique,
  label varchar(80) not null,
  active boolean not null default true,
  created_at timestamp not null default now()
);

create table residents (
  id bigint generated by default as identity primary key,
  house_id bigint not null references houses(id),
  name varchar(140) not null,
  email varchar(180) not null unique,
  phone varchar(40),
  document_masked varchar(40),
  gateway_customer_id varchar(120),
  status varchar(30) not null,
  created_at timestamp not null default now()
);

create table app_users (
  id bigint generated by default as identity primary key,
  name varchar(140) not null,
  email varchar(180) not null unique,
  password_hash varchar(255) not null,
  role varchar(30) not null,
  resident_id bigint references residents(id),
  active boolean not null default true,
  created_at timestamp not null default now()
);

create table settings (
  id bigint generated by default as identity primary key,
  village_name varchar(120) not null,
  monthly_amount numeric(12, 2) not null,
  payment_due_day integer not null,
  gateway_provider varchar(40) not null,
  webhook_secret varchar(180),
  created_at timestamp not null default now(),
  updated_at timestamp not null default now()
);

create table contributions (
  id bigint generated by default as identity primary key,
  house_id bigint not null references houses(id),
  resident_id bigint references residents(id),
  reference_month varchar(7) not null,
  amount numeric(12, 2) not null,
  paid_amount numeric(12, 2),
  status varchar(30) not null,
  payment_date timestamp,
  payment_method varchar(40),
  manual_payment boolean not null default false,
  manual_reason varchar(255),
  pix_charge_id bigint,
  created_at timestamp not null default now(),
  updated_at timestamp not null default now(),
  constraint uk_contributions_house_month unique (house_id, reference_month)
);

create table pix_charges (
  id bigint generated by default as identity primary key,
  contribution_id bigint not null references contributions(id),
  gateway varchar(40) not null,
  gateway_payment_id varchar(120) not null,
  external_reference varchar(120) not null,
  txid varchar(120),
  charge_value numeric(12, 2) not null,
  due_date date not null,
  status varchar(30) not null,
  qr_code_base64 text,
  pix_copy_paste text,
  invoice_url text,
  receipt_url text,
  created_at timestamp not null default now(),
  paid_at timestamp,
  updated_at timestamp not null default now(),
  constraint uk_pix_gateway_payment unique (gateway, gateway_payment_id)
);

alter table contributions
  add constraint fk_contributions_pix_charge foreign key (pix_charge_id) references pix_charges(id);

create table webhook_events (
  id bigint generated by default as identity primary key,
  gateway varchar(40) not null,
  event_id varchar(140) not null,
  event_type varchar(80) not null,
  gateway_payment_id varchar(120),
  payload_json text not null,
  processed boolean not null default false,
  processed_at timestamp,
  error_message varchar(500),
  created_at timestamp not null default now(),
  constraint uk_webhook_gateway_event unique (gateway, event_id)
);

create table expenses (
  id bigint generated by default as identity primary key,
  description varchar(220) not null,
  category varchar(80),
  amount numeric(12, 2) not null,
  expense_date date not null,
  supplier varchar(140),
  payment_method varchar(60),
  notes text,
  document_id bigint,
  service_order_id bigint,
  budget_id bigint,
  created_at timestamp not null default now()
);

create table service_orders (
  id bigint generated by default as identity primary key,
  title varchar(180) not null,
  description text not null,
  category varchar(80),
  priority varchar(30) not null,
  status varchar(40) not null,
  expected_value numeric(12, 2),
  final_value numeric(12, 2),
  supplier varchar(140),
  planned_date date,
  completed_date date,
  approved_budget_id bigint,
  notes text,
  created_by bigint,
  created_at timestamp not null default now(),
  updated_at timestamp not null default now()
);

create table budgets (
  id bigint generated by default as identity primary key,
  service_id bigint not null references service_orders(id),
  title varchar(180) not null,
  supplier varchar(140) not null,
  phone varchar(40),
  amount numeric(12, 2) not null,
  budget_date date,
  valid_until date,
  expected_date date,
  status varchar(40) not null,
  document_id bigint,
  notes text,
  created_by bigint,
  created_at timestamp not null default now(),
  updated_at timestamp not null default now()
);

create table documents (
  id bigint generated by default as identity primary key,
  name varchar(180) not null,
  type varchar(80) not null,
  url text not null,
  related_type varchar(60),
  related_id bigint,
  description text,
  created_at timestamp not null default now()
);

create index idx_pix_charges_status on pix_charges(status);
create index idx_contributions_reference_month on contributions(reference_month);
create index idx_webhook_payment_event on webhook_events(gateway_payment_id, event_type);
create index idx_budgets_service_id on budgets(service_id);
create index idx_documents_relation on documents(related_type, related_id);
